# This source is generated by AWS BOTO3 API. 
# It is used for learning purposes and is not profitable.
# S3 

### 전체 버킷 조회 
```
import boto3
s3 = boto3.resource('s3')
for bucket in s3.buckets.all():
        print(bucket.name)

```

### Access Key와 Secret Key 지정해서 전체 버켓 확인
```
import boto3
s3_res = boto3.resource('s3', aws_access_key_id="AKIAT9EOQZ9GJIIA6GMG", aws_secret_access_key="6oqkQhFJLKTOXkf7Z5ZEO67GKcmk3tGn2C3gFz6p", region_name='ap-northeast-2')
for bucket in s3_res.buckets.all():
        print(bucket.name)
```


### 버켓 파일과 스토리지 클래스 확인 
```
bucket_name = 'sungsuwebdata'
import boto3
s3_res = boto3.resource('s3')
each_bucket = s3_res.Bucket(bucket_name)
version = each_bucket.objects
for ver in version.all():
    print(ver.bucket_name)
    print(ver.key)
    print(ver.storage_class)
```

###